# Generated by Django 4.0.5 on 2022-07-20 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorRegister',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.BigIntegerField()),
                ('hospital_address', models.TextField()),
                ('password1', models.CharField(max_length=10)),
                ('password2', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'doctor_reg',
            },
        ),
        migrations.CreateModel(
            name='PainDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_pain_began', models.IntegerField()),
                ('onset_of_pain', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('comments', models.TextField()),
            ],
            options={
                'db_table': 'pain_details',
            },
        ),
        migrations.CreateModel(
            name='PainStartTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_at_work', models.BooleanField(default=False)),
                ('accident_at_home', models.BooleanField(default=False)),
                ('following_illness', models.BooleanField(default=False)),
                ('following_surgery', models.BooleanField(default=False)),
                ('road_traffic_accident', models.BooleanField(default=False)),
                ('pain_just_began', models.BooleanField(default=False)),
                ('others', models.TextField()),
            ],
            options={
                'db_table': 'pain_start',
            },
        ),
        migrations.CreateModel(
            name='PainTypeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('throbbing', models.BooleanField(default=False)),
                ('shooting', models.BooleanField(default=False)),
                ('stabbing', models.BooleanField(default=False)),
                ('sharp', models.BooleanField(default=False)),
                ('cramping', models.BooleanField(default=False)),
                ('gnawing', models.BooleanField(default=False)),
                ('hot_burning', models.BooleanField(default=False)),
                ('aching', models.BooleanField(default=False)),
                ('heavy', models.BooleanField(default=False)),
                ('tender', models.BooleanField(default=False)),
                ('splitting', models.BooleanField(default=False)),
                ('tiring_exhausting', models.BooleanField(default=False)),
                ('sickening', models.BooleanField(default=False)),
                ('fearful', models.BooleanField(default=False)),
                ('pushing_cruel', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'pain_type',
            },
        ),
        migrations.CreateModel(
            name='PatientRegister',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=50)),
                ('phone_number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('password1', models.CharField(max_length=10)),
                ('password2', models.CharField(max_length=10)),
                ('hospital_number', models.CharField(default='', max_length=20)),
                ('dateofbirth', models.CharField(default='', max_length=10)),
                ('address', models.TextField(default='')),
                ('postcode', models.CharField(default='', max_length=10)),
            ],
            options={
                'db_table': 'patient_reg',
            },
        ),
        migrations.CreateModel(
            name='TechRegister',
            fields=[
                ('tech_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.BigIntegerField()),
                ('address', models.TextField()),
                ('password1', models.CharField(max_length=10)),
                ('password2', models.CharField(max_length=10)),
                ('doctor_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctorregister')),
                ('patient_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patientregister')),
            ],
            options={
                'db_table': 'tech_reg',
            },
        ),
        migrations.AddField(
            model_name='doctorregister',
            name='patient_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patientregister'),
        ),
    ]
