# Generated by Django 4.0.5 on 2022-07-14 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorRegister',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.BigIntegerField()),
                ('hospital_address', models.TextField()),
                ('password1', models.CharField(max_length=10)),
                ('password2', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'doctor_reg',
            },
        ),
        migrations.CreateModel(
            name='PatientRegister',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=50)),
                ('phone_number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('password1', models.CharField(max_length=10)),
                ('password2', models.CharField(max_length=10)),
                ('hospital_number', models.CharField(default='', max_length=20)),
                ('dateofbirth', models.CharField(default='', max_length=10)),
                ('address', models.TextField(default='')),
                ('postcode', models.CharField(default='', max_length=10)),
            ],
            options={
                'db_table': 'patient_reg',
            },
        ),
        migrations.CreateModel(
            name='TechRegister',
            fields=[
                ('tech_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.BigIntegerField()),
                ('address', models.TextField()),
                ('password1', models.CharField(max_length=10)),
                ('password2', models.CharField(max_length=10)),
                ('doctor_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctorregister')),
                ('patient_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patientregister')),
            ],
            options={
                'db_table': 'tech_reg',
            },
        ),
        migrations.AddField(
            model_name='doctorregister',
            name='patient_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patientregister'),
        ),
    ]
