# Generated by Django 4.0.5 on 2022-07-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PainDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_pain_began', models.IntegerField()),
                ('pain_start', models.CharField(max_length=250)),
                ('others', models.CharField(max_length=250)),
                ('onset_of_pain', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('pain_now', models.CharField(max_length=250)),
                ('comments', models.TextField()),
            ],
            options={
                'db_table': 'pain_details',
            },
        ),
    ]
