# Generated by Django 4.0.5 on 2022-07-18 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_paindetails_patient_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paindetails',
            name='patient_fk',
        ),
    ]
