# Generated by Django 4.0.5 on 2022-07-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_paindetails_patient_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='PainStartTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_at_work', models.BooleanField(default=False)),
                ('accident_at_home', models.BooleanField(default=False)),
                ('following_illness', models.BooleanField(default=False)),
                ('following_surgery', models.BooleanField(default=False)),
                ('road_traffic_accident', models.BooleanField(default=False)),
                ('pain_just_began', models.BooleanField(default=False)),
                ('others', models.TextField()),
            ],
            options={
                'db_table': 'pain_start',
            },
        ),
        migrations.CreateModel(
            name='PainTypeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('throbbing', models.BooleanField(default=False)),
                ('shooting', models.BooleanField(default=False)),
                ('stabbing', models.BooleanField(default=False)),
                ('sharp', models.BooleanField(default=False)),
                ('cramping', models.BooleanField(default=False)),
                ('gnawing', models.BooleanField(default=False)),
                ('hot_burning', models.BooleanField(default=False)),
                ('aching', models.BooleanField(default=False)),
                ('heavy', models.BooleanField(default=False)),
                ('tender', models.BooleanField(default=False)),
                ('splitting', models.BooleanField(default=False)),
                ('tiring_exhausting', models.BooleanField(default=False)),
                ('sickening', models.BooleanField(default=False)),
                ('fearful', models.BooleanField(default=False)),
                ('pushing_cruel', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'pain_type',
            },
        ),
        migrations.RemoveField(
            model_name='paindetails',
            name='others',
        ),
        migrations.RemoveField(
            model_name='paindetails',
            name='pain_now',
        ),
        migrations.RemoveField(
            model_name='paindetails',
            name='pain_start',
        ),
        migrations.AlterField(
            model_name='paindetails',
            name='onset_of_pain',
            field=models.CharField(max_length=20),
        ),
    ]
